config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    collection do
      get 'top'=>'restaurants#top'
    end
    member do
      get 'chef'=> 'restaurants#chef'
    end
    resources :reviews, only: [:new, :create]
  end
  namespace :admin do
    resources :restaurants, only[:index]
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  validates :stars, inclusion: { in: [1,2,3], allow_nil: false, message: "stars must be 1 , 2 or 3" }
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/admin/restaurants_controller.rb
# app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  def index
    # Let's anticipate on next week (with login)
    @restaurants = user.restaurants.all
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :chef]

  def chef
  end

  def top
    @top_restaurants = Restaurant.where(stars: 3)

  end
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    # if @restaurant.save = true
    #   redirect_to restaurant_path(@restaurant)
    # else
    #   render :new
    # end


    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :description, :stars)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = Review.new

  end
  def create
    @review = review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)

  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])

  end
  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/index.hmtl.erb
<!-- # app/views/admin/restaurants/index.html.erb -->
<h1>My list of restaurants</h1>
<% @restaurants.each do |restaurant| %>
  <h2><%= restaurant.name %></h2>
  <p><%= restaurant.address %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScaffoldTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
</head>
<body>

<%= yield %>

</body>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stars %><br>
    <%= f.number_field :stars %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<!-- other options with simple form -->

<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :stars %>

  <%= f.button :submit %>
<% end %>

app/views/restaurants/chef.html.erb
<h2>Restaurant chef for <%= @restaurant.name %> is </h2>
<h3><%=@restaurant.chef%></h3>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Description</th>
      <th>Stars</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.description %></td>
        <td><%= restaurant.stars %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>
<%= link_to 'Top Restaurant', top_restaurants_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @restaurant.stars %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>
<%= link_to 'Chef', chef_restaurant_path(@restaurant) %>
<ul>
  <% @restaurant.reviews.each do |review|%>
  <li><%= review.content%></li>
  <% end %>
</ul>

app/views/restaurants/top.html.erb
<h1>Top restaurants</h1>
<ul>
<% @top_restaurants.each do|restaurant|%>
  <li><%=restaurant.name%></li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>New review for <%= @restaurant.name%></h1>
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label "content" %>
  <%= f.text_field :content %>
  <%= f.submit  %>
  <% end %>